# The URL the site will be built for
base_url = "https://bitbra.in"

# The theme to use
theme = "zola-dash"

title = "bitbrain"
minify_html = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# RSS Feed
generate_feeds = true

[markdown]
lazy_async_image = true

[markdown.highlighting]
theme = "dash"
extra_themes = ["themes/zola-dash/syntax_themes/dash.json"]
error_on_missing_language = true

[extra]
# Put all your custom variables here
homepage_title = "bitbrain"
homepage_subtitle = "Lead Software Engineer. Godot Engine evangelist."
homepage_img_url = "/images/hello-960.webp"

# Refer https://support.google.com/analytics/answer/9539598?hl=en
google_analytics_measurement_id = ""

[extra.homepage_image]
src = "/images/hello-960.webp"
srcset = "/images/hello-480.webp 480w, /images/hello-960.webp 960w"
sizes = "(min-width: 1024px) 50vw, 100vw"
author_sizes = "96px"
width = 960
height = 1707

[extra.footer]
enabled = true
prompt = "whoami"
theme_name = "zola-dash"
version = "v2"

# Both `url` and `icon` should be set for each entry
[[extra.social]]
url = "https://github.com/bitbrain"
icon = "lab la-github"

[[extra.social]]
url = "https://youtube.com/@bitbraindev"
icon = "lab la-youtube"

[[extra.social]]
url = "https://bsky.app/profile/bitbra.in"
icon = "las la-at"

[[extra.social]]
url = "https://mastodon.gamedev.place/@bitbraindev"
icon = "lab la-mastodon"


